extends:
  - ../../node_modules/s15e-javascript/.eslintrc.yml
  - plugin:ava/recommended

env:
  browser: true
  es6: true
  node: true

plugins:
  - ava

parserOptions:
  ecmaFeatures:
    jsx: true

rules:
  no-console:
    - off
  no-process-env:
    - off
