extends:
  - airbnb
  - plugin:ava/recommended
parser: babel-eslint
env:
  browser: true
  es6: true
  node: true
plugins:
  - ava
parserOptions:
  ecmaFeatures:
    jsx: true

root: true

rules:
  strict:
    - off
  no-console:
    - off
  semi:
    - off
  react/jsx-filename-extension:
    - off
  no-process-env:
    - off
  import/imports-first:
    - off
  import/newline-after-import:
    - off
  import/no-extraneous-dependencies:
    - off
  import/no-named-as-default:
    - off
  import/prefer-default-export:
    - off
  jsx-a11y/aria-props:
    - error
  jsx-a11y/heading-has-content:
    - off
  jsx-a11y/href-no-hash:
    - error
  jsx-a11y/label-has-for:
    - error
  jsx-a11y/mouse-events-have-key-events:
    - error
  jsx-a11y/role-has-required-aria-props:
    - error
  jsx-a11y/no-static-element-interactions:
    - off
  jsx-a11y/role-supports-aria-props:
    - error
  max-len:
    - off
  react/prefer-stateless-function:
    - off
  no-constant-condition:
    - off
  class-methods-use-this:
    - off
  react/prop-types:
    - off
  arrow-parens:
    - off
      
