extends:
  - airbnb
  - plugin:ava/recommended

env:
  browser: true
  es6: true
  node: true
plugins:
  - ava
parserOptions:
  ecmaFeatures:
    jsx: true

root: true

rules:
  no-console:
    - off
  semi:
    - off
  react/jsx-filename-extension:
    - off
  no-process-env:
    - off
  import/imports-first:
    - off
  import/newline-after-import:
    - off
  import/no-extraneous-dependencies:
    - off
  import/no-named-as-default:
    - off
  import/prefer-default-export:
    - off
