extends:
  - airbnb
  - plugin:ava/recommended

env:
  browser: true
  es6: true
  node: true
plugins:
  - ava
parserOptions:
  ecmaFeatures:
    jsx: true

root: true

rules:
  no-console:
    - off
  semi:
    - off
  react/jsx-filename-extension:
    - off
  no-process-env:
    - off
 import/imports-first:
   - off
