extends:
  airbnb

env:
  browser: true
  es6: true
  node: true

parserOptions:
  ecmaFeatures:
    jsx: true

rules:
  no-console:
    - off
  semi:
    - off
  react/jsx-filename-extension:
    - off
  no-process-env:
    - off
